clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-001.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-001.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-002.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-002.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-003.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-003.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-004.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-004.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-005.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-005.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-006.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-006.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-007.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-007.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-008.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-008.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-009.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-009.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-010.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-010.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-011.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-011.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-012.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-012.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-013.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-013.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-014.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-014.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-015.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-015.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-016.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-016.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-017.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-017.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-018.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-018.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-019.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-019.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-020.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-020.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-021.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-021.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-022.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-022.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-023.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-023.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-024.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-024.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-025.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-025.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-026.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-026.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-027.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-027.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-028.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-028.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-029.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-029.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-030.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-030.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-031.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-031.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-032.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-032.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-033.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-033.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-034.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-034.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-035.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-035.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-036.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-036.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-037.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-037.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-038.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-038.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-039.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-039.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-040.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-040.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-041.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-041.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-042.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-042.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-043.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-043.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-044.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-044.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-045.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-045.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-046.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-046.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-047.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-047.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-048.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-048.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-049.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-049.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-050.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-050.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-051.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-051.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-052.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-052.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-053.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-053.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-054.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-054.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-055.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-055.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-056.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-056.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-057.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-057.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-058.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-058.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-059.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-059.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-060.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-060.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-061.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-061.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-062.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-062.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-063.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-063.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-064.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-064.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-065.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-065.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-066.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-066.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-067.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-067.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-068.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-068.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-069.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-069.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-070.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-070.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-071.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-071.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-072.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-072.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-073.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-073.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-074.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-074.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-075.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-075.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-076.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-076.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-077.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-077.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-078.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-078.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-079.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-079.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-080.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-080.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-081.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-081.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-082.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-082.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-083.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-083.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-084.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-084.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-085.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-085.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-086.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-086.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-087.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-087.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-088.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-088.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-089.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-089.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-090.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-090.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-091.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-091.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-092.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-092.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-093.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-093.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-094.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-094.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-095.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-095.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-096.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-096.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-097.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-097.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-098.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-098.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-099.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-099.png'));
clear;close all; clc;
clean_img = main('G:/DATASETS/testimage_MSFPN/R100H/input/rain-100.png');
imwrite((clean_img), sprintf('results_R100H/out_%s','rain-100.png'));
