% clear;close all; clc;
% clean_img = main('G:/DATASETS/real_itnet/in/146.jpg');
% imwrite((clean_img), sprintf('results_real_itnet/out_%s','146.jpg'));
% clear;close all; clc;
% clean_img = main('G:/DATASETS/real_itnet/in/Image1.png');
% imwrite((clean_img), sprintf('results_real_itnet/out_%s','Image1.png'));
% clear;close all; clc;
% clean_img = main('G:/DATASETS/real_itnet/in/Image3.png');
% imwrite((clean_img), sprintf('results_real_itnet/out_%s','Image3.png'));
% clear;close all; clc;
% clean_img = main('G:/DATASETS/real_itnet/in/Image4.png');
% imwrite((clean_img), sprintf('results_real_itnet/out_%s','Image4.png'));
% clear;close all; clc;
% clean_img = main('G:/DATASETS/real_itnet/in/itnet19.jpg');
% imwrite((clean_img), sprintf('results_real_itnet/out_%s','itnet19.jpg'));
% clear;close all; clc;
% clean_img = main('G:/DATASETS/real_itnet/in/itnet22.jpeg');
% imwrite((clean_img), sprintf('results_real_itnet/out_%s','itnet22.jpeg'));
% clear;close all; clc;
% clean_img = main('G:/DATASETS/real_itnet/in/itnet23.jpg');
% imwrite((clean_img), sprintf('results_real_itnet/out_%s','itnet23.jpg'));
% clear;close all; clc;
% clean_img = main('G:/DATASETS/real_itnet/in/itnet25.jpg');
% imwrite((clean_img), sprintf('results_real_itnet/out_%s','itnet25.jpg'));
% clear;close all; clc;
% clean_img = main('G:/DATASETS/real_itnet/in/itnet27.jpg');
% imwrite((clean_img), sprintf('results_real_itnet/out_%s','itnet27.jpg'));
% clear;close all; clc;
% clean_img = main('G:/DATASETS/real_itnet/in/itnet29.jpg');
% imwrite((clean_img), sprintf('results_real_itnet/out_%s','itnet29.jpg'));
% clear;close all; clc;
% clean_img = main('G:/DATASETS/real_itnet/in/itnet31.jpg');
% imwrite((clean_img), sprintf('results_real_itnet/out_%s','itnet31.jpg'));
% clear;close all; clc;
% clean_img = main('G:/DATASETS/real_itnet/in/itnet35.jpg');
% imwrite((clean_img), sprintf('results_real_itnet/out_%s','itnet35.jpg'));
% clear;close all; clc;
% clean_img = main('G:/DATASETS/real_itnet/in/itnet36.jpg');
% imwrite((clean_img), sprintf('results_real_itnet/out_%s','itnet36.jpg'));
% clear;close all; clc;
% clean_img = main('G:/DATASETS/real_itnet/in/itnet37.jpg');
% imwrite((clean_img), sprintf('results_real_itnet/out_%s','itnet37.jpg'));
% clear;close all; clc;
% clean_img = main('G:/DATASETS/real_itnet/in/itnet41.jpg');
% imwrite((clean_img), sprintf('results_real_itnet/out_%s','itnet41.jpg'));
% clear;close all; clc;
% clean_img = main('G:/DATASETS/real_itnet/in/itnet43.jpg');
% imwrite((clean_img), sprintf('results_real_itnet/out_%s','itnet43.jpg'));
% clear;close all; clc;
% clean_img = main('G:/DATASETS/real_itnet/in/itnet51.jpg');
% imwrite((clean_img), sprintf('results_real_itnet/out_%s','itnet51.jpg'));
% clear;close all; clc;
% clean_img = main('G:/DATASETS/real_itnet/in/itnet53.jpg');
% imwrite((clean_img), sprintf('results_real_itnet/out_%s','itnet53.jpg'));
% clear;close all; clc;
% clean_img = main('G:/DATASETS/real_itnet/in/itnet60.jpg');
% imwrite((clean_img), sprintf('results_real_itnet/out_%s','itnet60.jpg'));
clear;close all; clc;
clean_img = main('G:/DATASETS/real_itnet/in/itnet73.jpg');
imwrite((clean_img), sprintf('results_real_itnet/out_%s','itnet73.jpg'));
clear;close all; clc;
clean_img = main('G:/DATASETS/real_itnet/in/itnet77.jpg');
imwrite((clean_img), sprintf('results_real_itnet/out_%s','itnet77.jpg'));
clear;close all; clc;
clean_img = main('G:/DATASETS/real_itnet/in/itnet82.jpg');
imwrite((clean_img), sprintf('results_real_itnet/out_%s','itnet82.jpg'));
clear;close all; clc;
clean_img = main('G:/DATASETS/real_itnet/in/itnet84.jpg');
imwrite((clean_img), sprintf('results_real_itnet/out_%s','itnet84.jpg'));
% clear;close all; clc;
% clean_img = main('G:/DATASETS/real_itnet/in/itnet88.jpg');
% imwrite((clean_img), sprintf('results_real_itnet/out_%s','itnet88.jpg'));
% clear;close all; clc;
% clean_img = main('G:/DATASETS/real_itnet/in/itnet_003.jpg');
% imwrite((clean_img), sprintf('results_real_itnet/out_%s','itnet_003.jpg'));
